name: pymeria
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pillow
  - click
  - requests
  - momentum
  - pytorch
  - torchvision
  - tqdm
  - matplotlib
  - scikit-learn
  - optuna
  - plotly
  - pandas
  - pip
  - pip:
    - loguru
    - transformers
    - projectaria-tools==1.5.5
    - kaleido 
    - -e .
