name: pymeria
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pillow
  - click
  - requests
  - momentum
  - pytorch
  - torchvision
  - tqdm
  - matplotlib
  - optuna
  - pip
  - pip:
    - loguru
    - projectaria-tools==1.5.5
    - -e .
