[workspace]
authors = ["Damir Tassybayev <tassybayev.kostanay@gmail.com>"]
channels = ["conda-forge", "nvidia", "pytorch", "https://prefix.dev/conda-forge"]
name = "nymeria_dataset"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = ">=2.2.5,<3"
pillow = ">=11.1.0,<12"
click = ">=8.1.8,<9"
requests = ">=2.32.3,<3"
tqdm = ">=4.67.1,<5"
momentum = ">=0.1.38,<0.2"
pip = ">=25.1,<26"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
opencv = ">=4.11.0,<5"
torchvision = ">=0.21.0,<0.22"
pytorch = ">=2.6.0,<3"

[pypi-dependencies]
loguru = ">=0.7.3, <0.8"
projectaria-tools = "==1.5.5"
rerun-sdk = "==0.23.1"
mediapipe = ">=0.10.14, <0.11"
